name: gallery_cleaner
description: "Gallery Cleaner - Clean your gallery with ease"
publish_to: "none"

version: 1.0.2+23

environment:
  sdk: ^3.11.0-57.0.dev
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  go_router: ^14.2.0
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.1.3
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^18.0.1
  photo_manager: ^3.2.0
  permission_handler: ^11.3.1
  animations: ^2.0.11
  path_provider: ^2.1.3
  logger: ^2.4.0
  intl: ^0.20.2
  lottie: ^3.1.0
  shared_preferences: ^2.3.3
  flutter_secure_storage: ^9.2.2
  audioplayers: ^6.0.0
  google_mobile_ads: ^5.1.0
  in_app_purchase: ^3.2.0
  purchases_flutter: ^9.0.0
  crypto: ^3.0.5
  image: ^4.3.0
  url_launcher: ^6.3.1
  flutter_dotenv: ^5.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    - assets/lottie/loading.json
    - assets/lottie/gallery_loading.json
    - assets/lottie/duplicate.json
    - assets/lottie/blıur.json
    - assets/lottie/left.json
    - assets/lottie/right.json
    - assets/lottie/trash.json
    - assets/lottie/keep_photo.json
    - assets/lottie/wipe.json
    - assets/sound/delete.mp3
    - assets/sound/keep.mp3
    - assets/sound/scanner.mp3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/icon-blue.png
  min_sdk_android: 21
  remove_alpha_ios: true
